### ISSUE TITLE
posts/2023/2023h1-sharing/

### ISSUE THREAD

**Issue by stavhaygn** [yctseng1227/yctseng1227.github.io#17]
終於更新了！🎉
但沒有留言區，只好留 issue

我也有更新筆記在 blog 上（其實只是漢化 ...
https://stavhaygn.tw/docs/

未來再寫心得或日記

**Comment by yctseng1227** [comment]
Blog 搬家還沒把留言區的功能搬過來，希望不會是永生之年系列😃 
我前幾天有發現的你的 Blog 有 commit 紀錄，想想也該是時候開張了吧 👍

**Comment by yctseng1227** [comment]
The comment feature has been released 🥳
