### ISSUE TITLE
Please help me update my website in your post:(

### ISSUE THREAD

**Issue by john850512** [yctseng1227/yctseng1227.github.io#2]
Hi, 偶然發現我以前的部落格網站有出現在你的[【分享】那些關於研究所推甄的大小事 🐾🐾🐾](https://yctseng1227.github.io/190411-master-recommend-impression/#more)文章中，

感謝引用我的文章，不過前陣子我換部落格了，再努力提升做SEO中QQ 
能否幫我把我的部落格網址耕換成新的網址呢，感謝感謝

附上該篇文章的新網址: [[研究所推甄]資工所推甄心得1-備審準備](https://meetonfriday.com/posts/44bbe391/)

**Comment by yctseng1227** [comment]
Of course, thanks for your response.
